### ISSUE TITLE
Conversion error

### ISSUE THREAD

**Issue by SpongebobSquamirez** [FooSoft/yomichan-import#17]
I'm on windows 10 64-bit, trying to import an EPWING, and I get this error:

2018/04/30 02:08:18 conversion process failed: failed to find compatible extractor for 'ＮＨＫ　日本語発音アクセント辞典'

The path itself and all the files within are written in normal characters, but the actual dictionary is named as above, and I'm not sure how to safely change that information (but I assume it's coming from within the CATALOGS file), or if that is what is causing the problem.

Here is the relevant part of my dictionary source path: NHK Accent\NHKACT\NHKACT\CATALOGS
And I made up this path for the zip (it doesn't exist yet): yomichan_dicts\nhkaccent.zip

**Comment by FooSoft** [comment]
This is because the dictionary file you are trying to import is not supported by yomichan-import. You see, while the EPWING text data can be extracted for any dictionary, regular expressions have to be written to parse out useful data out of the text blobs that you get back. The list of currently supported dictionaries can be found in `README.md`
