### ISSUE TITLE
[feature request] ignore English or alphanumeric entries

### ISSUE THREAD

**Issue by ghost** [FooSoft/yomichan-import#7]
It would be great if I could pass in a command line flag to ignore english or alphanumeric entries.

The yomichan extension can get annoying when I type into a text box and hit Shift while my cursor happens to be hovering over an English word contained in an EPWING entry.

**Comment by FooSoft** [comment]
I think this would make more sense to do on the Yomichan side by blocking search of strings that contain non Hiragana/Katakana/Kanji characters. 

Due to issues with shoddy IndexedDB implementation in Chrome, deleting individual dictionaries is not viable. This means that upon discovering that matches to alphanumeric entries are annoying, the user would have to nuke their database and re-import everything, which is a pretty bad workflow.

**Comment by ghost** [comment]
Yeah that's a good point I'm fine with this functionality being placed into Yomichan although I haven't looked at the Yomichan code at all and have no desire to do those changes there myself.

I'll close this up and make a new issue there.

EDIT: Cotinued here https://github.com/FooSoft/yomichan/issues/47

P.S. as I was typing up this response the exact scenario of the text box popping up because my cursor happened to be hovering over a word happened -_-
